env:
  API_ID: ${{ secrets.API_ID }}
  API_HASH: ${{ secrets.API_HASH }}
  PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
  GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
